name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
   on:
     workflow_dispatch:
     pull_request:
         branches:
             - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v2
      env:
        SP_JSON: ${{ secrets.AZURE_CREDENTIALS }}
      with:
        creds: ${{ env.SP_JSON }}

    - name: Run Azure Machine Learning training job
      run: az ml job create -f src/job.yml --stream --resource-group rg-ai300-l87641045a7be45f5aa --workspace-name mlw-ai300-l87641045a7be45f5aa
